question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Music",
        "question": "Dave Grohl recorded the Foo Fighters&#039; debut, &quot;Foo Fighters,&quot; by himself.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "History",
        "question": "The two atomic bombs dropped on Japan by the United States in August 1945 were named &#039;Little Man&#039; and &#039;Fat Boy&#039;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "There are 2 player roles in Trouble in Terrorist Town.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Music",
        "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": r"Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Art",
        "question": "The Statue of Liberty&#039;s official name is &ldquo;Liberty Enlightening the World&rdquo;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "You can legally drink alcohol while driving in Mississippi.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Music",
        "question": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Entertainment: Video Games",
        "question": "Unturned originally started as a Roblox game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Greenland is covered with grass and Iceland covered with ice.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Geography",
        "question": "Only one country in the world starts with the letter Q.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
